### ISSUE TITLE
vim-gutentags E518: Unknown option: cscopeprg=gtags-cscope

### ISSUE THREAD

**Issue by fzhzhen1987** [dhananjaylatkar/cscope_maps.nvim#1]
Due to the removal of cscope in nvim 0.9, I have to use the cscope_maps plugin, but
I would like to use the vim-gutentags plugin and request support for vim-gutentags in the cscope_maps.

**Comment by dhananjaylatkar** [comment]
Hi @fzhzhen1987 
Can you please elaborate? AFAIK `vim-gutentags` works with `ctags` and `ctags` support is not removed from 0.9.

**Comment by dhananjaylatkar** [comment]
Upon carefully looking into `vim-gutentags` I realized that it indeed supports `cscope`.
I have created module for `cscope_maps` in `vim-gutentags` and it seems to work. I'll need help to test it by people who actually know their way around `vim-gutentags`.

I'll open PR soon.

**Comment by dhananjaylatkar** [comment]
https://github.com/ludovicchabant/vim-gutentags/pull/346

**Comment by fzhzhen** [comment]
thx. i have found another way to use gtags-cscope. This issue should be closed.

**Comment by dhananjaylatkar** [comment]
Would you mind sharing what you are using so that others can do the same.

Anyway, my new module in vim-gutentags does the job. If anyone's is interested, may use my fork until it's merged in mainline.

**Comment by adityaseven** [comment]
@fzhzhen 
Please do share I am interested as well

**Comment by dhananjaylatkar** [comment]
Packer config to use my gutentags patch
```lua
use({
	"dhananjaylatkar/vim-gutentags",
	after = "cscope_maps.nvim",
	config = function()
		vim.g.gutentags_modules = {"cscope_maps"} -- This is required. Other config is optional
		vim.g.gutentags_cscope_build_inverted_index_maps = 1
		vim.g.gutentags_cache_dir = vim.fn.expand("~/code/.gutentags")
		vim.g.gutentags_file_list_command = "fd -e c -e h"
		-- vim.g.gutentags_trace = 1
	end,
})

```
