### ISSUE TITLE
"tag stack empty" error when I want to back previous position.

### ISSUE THREAD

**Issue by spring-cxz** [dhananjaylatkar/cscope_maps.nvim#11]
Hi, there
    I'm glade to find cscope_maps.vim to use on neovim after v0.9 version. It's very useful to me. 
    But I encountered a problem.  When I  goto one function definition by cscope_map over telescope or quickfix, and use 'Crtl+t' go back previous position, the "E73: tag stack empty" error info come out. 
    I don't know what's wrong. Have you ever encountered this problem？ 
                             Thanks

The config:
![image](https://github.com/dhananjaylatkar/cscope_maps.nvim/assets/52104372/3e7471a0-e038-410e-9ff2-35d9ef47cac9)

![image](https://github.com/dhananjaylatkar/cscope_maps.nvim/assets/52104372/ec232c9d-f2c2-4b92-be96-59481b8faf60)

The error info
![image](https://github.com/dhananjaylatkar/cscope_maps.nvim/assets/52104372/16fd90e8-4f34-42b2-a4d7-e06dc10c8e7c)

**Comment by dhananjaylatkar** [comment]
I have added tagstack push logic and <kbd>C-t</kbd> should work as expected.
Commit: https://github.com/dhananjaylatkar/cscope_maps.nvim/commit/46e1942f675a4d9ab1779ba0adb2556de345c11c
