### ISSUE TITLE
Can't use telescope

### ISSUE THREAD

**Issue by katcherw** [dhananjaylatkar/cscope_maps.nvim#12]
I just started using cscope_maps, and everything seems to work fine, but I can't get telescope to work.

My original config was (using lazy):

```
 {
     'dhananjaylatkar/cscope_maps.nvim',
     dependencies = {"folke/which-key.nvim", 'nvim-telescope/telescope.nvim'},
     opts = {
       cscope = {
          db_file = "/home/proj/cscope.out",
          exec = "cscope",
          picker = "telescope",
          skip_picker_for_single_result = false,
          db_build_cmd_args = { "-bqv" },
        }
      }
  },
```
But the selection screen went to the quickfix window instead of telescope. I saw in somebody else's config they were using `use_telescope = true`, so I tried adding that next. This time I saw the telescope window come up, but it wasn't populated, and I got the following error:

```
[telescope] [WARN  13:19:42] ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:489: Finder failed with msg:  ...im/lazy/cscope_maps.nvim/lua/cscope/telescope_picker.lua:22: attempt to get length of local 'icon' (a nil va
lue)
[telescope] [WARN  13:20:04] ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:489: Finder failed with msg:  ...im/lazy/cscope_maps.nvim/lua/cscope/telescope_picker.lua:22: attempt to get length of local 'icon' (a nil va
lue)
```
This is the version of nvim:
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by dhananjaylatkar** [comment]
Hi @katcherw ,

I'm not able to reproduce this issue. 
I'm suspecting it could be problem with devivons not loading properly. Can you add `"nvim-tree/nvim-web-devicons"` as dependency and verify?

**Comment by katcherw** [comment]
I added `"nvim-tree/nvim-web-devicons"` as a dependency but I still get the same error. Also, I am already using nvim-web-devicons for NeoTree and it is working fine.

**Comment by katcherw** [comment]
It looks like it was some update issue. I updated all my packages, exited and restarted, and then it started to work. Thanks!
