### ISSUE TITLE
This update of lua-fzf will cause the plugin to malfunction.

### ISSUE THREAD

**Issue by SunJun8** [dhananjaylatkar/cscope_maps.nvim#15]
[feat(highlights): added new default highlights groups:](https://github.com/ibhagwan/fzf-lua/commit/8b6181b3977ad16cb5ca9d8f14b0849c8d1d708a#diff-1bd9dd4469ea92555606909422bbfe5a2d865a3b2ed6ea8e5f509bd14a4416e1R271)

**Comment by dhananjaylatkar** [comment]
Hi @SunJun8 

I'm on [fzf-lua 0cb40d4](https://github.com/ibhagwan/fzf-lua/commit/0cb40d488670f0af8011338bbcedd1319a277104) and don't see any issue.

Can you share the error msg?

**Comment by SunJun8** [comment]
> Hi @SunJun8
> 
> I'm on [fzf-lua 0cb40d4](https://github.com/ibhagwan/fzf-lua/commit/0cb40d488670f0af8011338bbcedd1319a277104) and don't see any issue.
> 
> Can you share the error msg?

There is no problem now, it should have been fixed in [feat(highlights): major refactor, see below](https://github.com/ibhagwan/fzf-lua/commit/f09d475c3#diff-1bd9dd4469ea92555606909422bbfe5a2d865a3b2ed6ea8e5f509bd14a4416e1R136)

**Comment by dhananjaylatkar** [comment]
Thanks @SunJun8 for bringing my attention to this commit.

I tried using `ansi_from_hl()` but those colors are not as vibrant as `ansi_codes()`.
Maybe if `ansi_codes()` is removed altogether, I'll move to `ansi_from_hl()`.
