### ISSUE TITLE
What is the font in the readme's image?

### ISSUE THREAD

**Issue by onriv** [dhananjaylatkar/cscope_maps.nvim#17]
May I ask what is the font in the image?

![image](https://github.com/dhananjaylatkar/cscope_maps.nvim/assets/1629055/6e632f88-5d2b-4e9f-9c0a-e1110655b1e6)

Thank you very much.

**Comment by dhananjaylatkar** [comment]
Hurmit Nerd Font
https://www.programmingfonts.org/#hermit
