### ISSUE TITLE
The picker telescope and lua-fzf got hang when the variable has multi underscore

### ISSUE THREAD

**Issue by waynecw** [dhananjaylatkar/cscope_maps.nvim#19]
I tried to run 
```
Cscope find g __sk_buff
```
in the linux kernel source tree, some of the pickers were hanging.
- quickfix - ok
- telescope - hung
- lua-fzf - hung

**Comment by dhananjaylatkar** [comment]
Cause is not multi underscore but **treesitter**.

file - tools/include/uapi/linux/bpf.h

If you try to open result in quickfix, nvim hangs.
nvim hangs when opening/previewing this file.
I'm not even able to open this file in nvim when treesitter is turned on. 
```
➜ nvim tools/include/uapi/linux/bpf.h
```

I'll advise turning off treesitter for now and raise issue in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter)

**Comment by dhananjaylatkar** [comment]
nvim-treesitter/nvim-treesitter#5227

**Comment by waynecw** [comment]
Thank you!!

**Comment by waynecw** [comment]
I can open the `bpf.h` in nvim without issues, but when telescope runs as a picker to show the file, nvim is hanging. So it sounds like a different issue between us?

**Comment by dhananjaylatkar** [comment]
Do you lazy load treesitter? My config loads it on BufRead event.

**Comment by waynecw** [comment]
I believe so, I didn't put customized config but just the default config below
```
use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
```

**Comment by dhananjaylatkar** [comment]
@waynecw 
Lazy loading doesn't affect it (I tried with and without)

Can you try on latest nvim nighlty? It has some improvements for injection handler neovim/neovim#24647

**Comment by waynecw** [comment]
I tried nvim nightly but still got hang.

Below is my step.

1. Checkout libbpf from https://github.com/libbpf/libbpf. My git hash is at `05f94ddbb837f5f4b3161e341eed21be307eaa04`.
2. Run `cscope -R -q -k`
3. Check nvim version
```
nvim --version
NVIM v0.10.0-dev-800+g3d948a4dc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
4. In nvim, run `PackerSync` to make sure plugins are the latest
5. In nvim, run `Cscope find g bpf_sock`. 
6. In telescope picker, select the file `include/uapi/linux/bpf.h`, then nvim hangs

**Comment by dhananjaylatkar** [comment]
You are not on latest nightly. `g3d948a4dc` doesn't contain injection handler patch.
`gc0ac53e0d` is the latest one as of this moment.

**Comment by waynecw** [comment]
I switched to `gc0ac53e0d` and now it works perfectly, thanks a lot!
