### ISSUE TITLE
skip_picker_for_single_result = true

### ISSUE THREAD

**Issue by zhenggangpku** [dhananjaylatkar/cscope_maps.nvim#20]
Thank you for inventing this plugin, and I am also very lucky to mention the first issue ----" skip_picker_for_single_result does not work when it is set to true, and it still needs to be selected when there is only one result.

**Comment by dhananjaylatkar** [comment]
@zhenggangpku It is working for me.
Can you share your config?

**Comment by zhenggangpku** [comment]
> @zhenggangpku It is working for me. Can you share your config?

zgCsm = require("cscope_maps")
local cscope_opts = {
   -- maps related defaults
   disable_maps = false, -- "true" disables default keymaps
   skip_input_prompt = true, -- "true" doesn't ask for input

   -- location of cscope db file
   db_file = "./cscope.out",
   -- cscope executable
   exec = "cscope", -- "cscope" or "gtags-cscope"
   -- choose your fav picker
   picker = "quickfix", -- "telescope", "fzf-lua" or "quickfix"
   -- "true" does not open picker for single result, just JUMP
   skip_picker_for_single_result = true, -- "false" or "true"
   -- these args are directly passed to "cscope -f <db_file> <args>"
   db_build_cmd_args = { "-bqkv" },
   -- statusline indicator, default is cscope executable
   statusline_indicator = nil,
}
zgCsm.setup(cscope_opts)


-- tks a lot

**Comment by dhananjaylatkar** [comment]
cscope related options should be in `cscope` table. See default config
```lua
{
  -- maps related defaults
  disable_maps = false, -- "true" disables default keymaps
  skip_input_prompt = false, -- "true" doesn't ask for input

  -- cscope related defaults
  cscope = {
    -- location of cscope db file
    db_file = "./cscope.out",
    -- cscope executable
    exec = "cscope", -- "cscope" or "gtags-cscope"
    -- choose your fav picker
    picker = "quickfix", -- "telescope", "fzf-lua" or "quickfix"
    -- "true" does not open picker for single result, just JUMP
    skip_picker_for_single_result = false, -- "false" or "true"
    -- these args are directly passed to "cscope -f <db_file> <args>"
    db_build_cmd_args = { "-bqkv" },
    -- statusline indicator, default is cscope executable
    statusline_indicator = nil,
  }
}
```

**Comment by zhenggangpku** [comment]
> 
I made a mistake, it works fine now, thanks, this plugin is awesome!

**Comment by dhananjaylatkar** [comment]
> this plugin is awesome!

Thanks!
