### ISSUE TITLE
Cscope and  Cstag  were failed to create using vim-plug manager

### ISSUE THREAD

**Issue by littlecarpenter** [dhananjaylatkar/cscope_maps.nvim#21]
**Describe the bug**

**To Reproduce**
.vimrc:
`Plug 'folke/which-key.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'ibhagwan/fzf-lua'
Plug 'nvim-tree/nvim-web-devicons'
Plug 'dhananjaylatkar/cscope_maps.nvim'
Plug 'ludovicchabant/vim-gutentags'`

**Expected behavior**
:Cscope  can be poped

**Screenshots**

**nvim version (please complete the following information):**
nvim -v
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

**cscope_maps config (please complete the following information):**
using  default config

**Additional context**

**Comment by dhananjaylatkar** [comment]
Did you do `require("cscope_maps").setup()`?
Can you paste your minimal config to re-create the issue?

**Comment by littlecarpenter** [comment]
> require("cscope_maps").setup()

This issue is fixed after adding this config, Many thanks
