### ISSUE TITLE
Quit Neovim spent too long

### ISSUE THREAD

**Issue by gaslight217** [dhananjaylatkar/cscope_maps.nvim#25]
**Describe the bug**
_I have loaded cscope_maps.nvim and vim-gutentags, I've try series functions of "cscope -g", it's working well. However, when I save my change, and enter ":wq", neovim hang._  

**To Reproduce**
1. cscope -Rbq
2. nvim xx.c, do some changes
3. :wq
4. neovim hang

**nvim version (please complete the following information):**
NVIM v0.9.4

**cscope_maps config (please complete the following information):**
local cscope = require 'cscope_maps'
cscope.setup = {
  skip_input_prompt = true, -- "true" doesn't ask for input
  prefix = "<leader>c", -- prefix to trigger maps

  cscope = {
    exec = "cscope", -- "cscope" or "gtags-cscope"
    -- choose your fav picker
    picker = "telescope",
    skip_picker_for_single_result = false, 
    db_build_cmd_args = { "-bqkv" },
  }
}

**Additional context**

1. I beleve it's caused by vim-gutentags, cause when i disable it, it's will be normal for nvim's quit
2. It's not hang after by checking, it spends too long for about 1min

**Comment by dhananjaylatkar** [comment]
I too observed this when using gutentags. It was because gutentangs was also indexing cscope.out file. Can you check if cscope.out is in cscope.files created by gutentags?

If you have `fd`, use `vim.g.gutentags_file_list_command = "fd -e c -e h"` to list files. It's faster than `find`.

**Comment by dhananjaylatkar** [comment]
Other option is, rebuild DB using `:Cscope build` or `<prefix>cb`.

You can also create autocmd for running `:Cscope build` after saving `.c` and `.h` files.
e.g
```lua
local group = vim.api.nvim_create_augroup("CscopeBuild", { clear = true })
vim.api.nvim_create_autocmd("BufWritePost", {
  pattern = { "*.c", "*.h" },
  callback = function ()
    vim.cmd("Cscope build")
  end,
  group = group,
})

```

**Comment by gaslight217** [comment]
> fd -e c -e h

Thanks, It helps a lot, could you help update it in README？

Otherwise, I've set it with https://github.com/dhananjaylatkar/cscope_maps.nvim#config-for-vim-gutentags, but it's useless, finally it work for I revised "plat/unix/update_scopedb.sh"

**Comment by dhananjaylatkar** [comment]
Sorry, I didn't understand what you are trying to say.
Is gutentags config in Readme not working? Because I suggested same 'fd' command from there.
