### ISSUE TITLE
how to get cscope working from any directory

### ISSUE THREAD

**Issue by psk243** [dhananjaylatkar/cscope_maps.nvim#27]
**Describe the bug**

I have created cscope database in the project root directory. The cscope does not work from inside directories of the project root

**To Reproduce**
1. create cscope data base in project root directory
2. cd <child directory>
3. open a file and try to invoke cscope for any symbol. 

**Expected behavior**
It should identify the cscope.out in project root (recurisve search like tags) and work

**Screenshots**

**nvim version (please complete the following information):**
nvim -v
NVIM v0.9.5
Build type: Release

**cscope_maps config (please complete the following information):**
```lua
  require('cscope_maps').setup {
        -- your configuration options here
        disable_maps = true, -- "true" disables default keymaps
        skip_input_prompt = true, -- don't ask for "YES" before jump
        cscope = {
                picker = "telescope",
        }
  }
```

**Comment by dhananjaylatkar** [comment]
Hi @psk243 

I have implemented this feature. (6dbe79c217e13f4cf540f3dde45da1921f555b7d)

Update the plugin and enable `project_rooter` config (check [README](https://github.com/dhananjaylatkar/cscope_maps.nvim/blob/main/README.md)),

**Comment by psk243** [comment]
Thank you for implementing this. It works like a charm.

couple of things :

- The log message added saying directory is changed is quite annoying. I always have to hit ENTER. I just commented it out for now. is there way this can be suppressed without editing the code or you can make a change in code?
- 
- when change directory is disabled but project root is enabled, it works. However, the file path is shown as absolute due to which we actually don't see the leaf dir or file in which this symbol is present. if we use telescope as picker, it is difficult to search further..all the time we see /abc/def/ghi/..... not the xyz.c file. can you please add a relative path. for now, I am using changdir option to true . I am reporting this as a feedback only.

Thanks again for your help with this feature. I have recently upgraded to nevoid 0.9 and without your csscope plugin, I just can't use neovim.

**Comment by dhananjaylatkar** [comment]
Thanks for trying it quickly.

#1 I didn't realise that it asks for ENTER every time. I'll remove it.

#2 Yeah. I observed the same and that's why I added option to change cwd. 
Relative path function from plenary.nvim doesn't do `../another_dir/file.c`. It only removes common part of path. I may have to find something else or write on my own.
