### ISSUE TITLE
Vim-gutentags doesn't work when use with gtags-cscope.

### ISSUE THREAD

**Issue by LimbicSys** [dhananjaylatkar/cscope_maps.nvim#28]
**Describe the bug**
```
use({
	"dhananjaylatkar/vim-gutentags",
	after = "cscope_maps.nvim",
	config = function()
		vim.g.gutentags_modules = {"cscope_maps"} -- This is required. Other config is optional
		vim.g.gutentags_cscope_build_inverted_index_maps = 1
		vim.g.gutentags_cache_dir = vim.fn.expand("~/code/.gutentags")
		vim.g.gutentags_file_list_command = "fd -e c -e h"
		-- vim.g.gutentags_trace = 1
	end,
})
```
The setting doesn't work with gtags-cscope.
https://github.com/ludovicchabant/vim-gutentags/pull/346 The PR only added support for cscope.
I guess something like `autoload/gutentags/gtags_cscope.vim` is needed.

**nvim version (please complete the following information):**
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info

**cscope_maps config (please complete the following information):**
```lua
opts = {
      cscope = {
        exec = "gtags-cscope",
      },
}
```

**Comment by dhananjaylatkar** [comment]
Alternative to gutentags is, rebuild DB using `:Cscope build` or `<prefix>cb`.

You can also create autocmd for running `:Cscope build` after saving .c and .h files.
e.g

```lua
local group = vim.api.nvim_create_augroup("CscopeBuild", { clear = true })
vim.api.nvim_create_autocmd("BufWritePost", {
  pattern = { "*.c", "*.h" },
  callback = function ()
    vim.cmd("Cscope build")
  end,
  group = group,
})
```
