### ISSUE TITLE
:Cscope find    invocation can not regcognize space in string 

### ISSUE THREAD

**Issue by wangfanstar** [dhananjaylatkar/cscope_maps.nvim#31]
**Describe the bug**
The invocation ":Cscope find t" is unable to recognize spaces, for instance: ":Cscope find t aaa bbb" fails to recognize "aaa bbb", and even adding quotation marks "\"" does not make it effective.
In the old version of ":cscope find t", it was possible to recognize spaces.

**To Reproduce**

**Expected behavior**
behavior like old cscope find 

**Screenshots**

**nvim version (please complete the following information):**
nvim -v
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

**cscope_maps config (please complete the following information):**
```lua
lua << EOF
require("cscope_maps").setup({
    disable_maps = false, 
    prefix = "<leader>s",
    -- cscope related defaults
    cscope = {
        -- location of cscope db file
        db_file = "./cscope.out",
        -- cscope executable
        exec = "gtags-cscope", -- "cscope" or "gtags-cscope"
        -- choose your fav picker
        picker = "quickfix", -- "telescope", "fzf-lua" or "quickfix"
        -- size of quickfix window
        qf_window_size = 5, -- any positive integer
        -- position of quickfix window
        qf_window_pos = "bottom", -- "bottom", "right", "left" or "top"
        -- "true" does not open picker for single result, just JUMP
        skip_picker_for_single_result = false, -- "false" or "true"
        -- these args are directly passed to "cscope -f <db_file> <args>"
        db_build_cmd_args = { "-bqkv" },
        -- statusline indicator, default is cscope executable
        statusline_indicator = nil,
        -- try to locate db_file in parent dir(s)
        project_rooter = {
            enable = false, -- "true" or "false"
            -- change cwd to where db_file is located
            change_cwd = false, -- "true" or "false"
        },
    }
})
```

**Additional context**

**Comment by dhananjaylatkar** [comment]
Hi @wangfanstar,
You can escape space char using `\`
For example, `:Cscope find t aaa\ bbb`.

PS. I would suggest using fuzzy finder (like telescope.nvim) for text search. It is interactive and fast.

**Comment by wangfanstar** [comment]
I use \  :Cscope find t aaa\ bbb,  but result is not correct include "aaa bbb",  the way I want to use cscope find text is to use :cnext to iterate the result  after change the text "aaa bbb" to "aaa ccc",  the  fuzzy finder must repeat find text , not convient as :cnext

**Comment by dhananjaylatkar** [comment]
Hi @wangfanstar 

I have added ability to accept spaces. Please update and try it out.
`:Cs f t aaa bbb` -> notice `\` is not required

**Comment by wangfanstar** [comment]
> Hi @wangfanstar
> 
> I have added ability to accept spaces. Please update and try it out. `:Cs f t aaa bbb` -> notice `\` is not required

the new version works correction, thanks!
