### ISSUE TITLE
adding multiple cscope.outs to the cscope, such as "cscope - f cscope1. out - f cscope2. out"

### ISSUE THREAD

**Issue by zhenggangpku** [dhananjaylatkar/cscope_maps.nvim#34]
Hello boss, I am eager for a feature that requires adding multiple cscope.outs to the cscope, such as "cscope - f cscope1. out - f cscope2. out". My current temporary approach is to add an additional "- f cscope2. out" to the configuration item db_file, and modify your code cscope_maps.nvim/lua/cscope/init.lua by commenting out the "if vim. loop. fs_stat (db_file)==nil then" section. If you can support a list of cscope.outs, that would be great. Thank you very much.

**Comment by dhananjaylatkar** [comment]
This is one of the thing missing from this port. I'll add it next week.
Thanks!

**Comment by dhananjaylatkar** [comment]
Hi @zhenggangpku 

I have added this feat (0f11a2fed38828add4a2b10d25715d3549310902).

Try it out and provide feedback.

Bonus feat (cbd7999a01cfb42be04fecf85e9ae3e0c08bd2fe) is also added where you can add/remove db files on the fly using `:Cs db add <files>` and `Cs db rm <files>`

**Comment by zhenggangpku** [comment]
> Hi @zhenggangpku
> 
> I have added this feat ([0f11a2f](https://github.com/dhananjaylatkar/cscope_maps.nvim/commit/0f11a2fed38828add4a2b10d25715d3549310902)).
> 
> Try it out and provide feedback.
> 
> Bonus feat ([cbd7999](https://github.com/dhananjaylatkar/cscope_maps.nvim/commit/cbd7999a01cfb42be04fecf85e9ae3e0c08bd2fe)) is also added where you can add/remove db files on the fly using `:Cs db add <files>` and `Cs db rm <files>`

it worked, nice job!  thank you very much!
