### ISSUE TITLE
Add preview support in CsStackView

### ISSUE THREAD

**Issue by its-izhar** [dhananjaylatkar/cscope_maps.nvim#36]
I use cscope_maps quite frequently and it's an amazing plugin. Been using it for a while now with telescope picker.

I wanted to request for a feature to enhance `CsStackView` to display preview with the chosen picker. As it is, `CsStackView` command is pretty useful to quickly familiarize yourself with the call hierarchy, especially with a new codebase. Adding the ability to display a "grep preview" side by side to the call tree would be super helpful to understand the context around the code.

Please consider this, it would be a good value add to this amazing plugin.

Thanks!

**Comment by dhananjaylatkar** [comment]
Sure. This will be good enhancement.

**Comment by dhananjaylatkar** [comment]
Hi @its-izhar 

I have added this feature. Try and provide feedback.
