### ISSUE TITLE
Add support for pre-path

### ISSUE THREAD

**Issue by mmaret-psee** [dhananjaylatkar/cscope_maps.nvim#38]
**Is your feature request related to a problem? Please describe.**
The Vim cscope support the pre-path option to use database build relatively to a given directory.

```
	USAGE	:cs add {file|dir} [pre-path] [flags]
	    [pre-path] is the pathname used with the -P command to cscope.
```

This is useful for large codebase where you have cscope db for subfolders

**Describe the solution you'd like**
add an option to `cscope db add` 

**Describe alternatives you've considered**
Using project_root option but it is not supposed to work with alternative db

**Additional context**

**Comment by dhananjaylatkar** [comment]
hi
can you provide example of how this works.

**Comment by mmaret-psee** [comment]
Sure! I'll try to make something understandable :)
Here is a simplified example of a worktree

```
├── mainwork
│   └── main.c
├── subfold1
│   ├── cscope.out
│   ├── file1.c
│   └── file2.c
└── subfold2
    ├── file1.c
    └── file2.c
```

The subfold1 contains cscope file for the important submodule. We may imagine that there is also subfolder2,3, 4 .... that contains a lot of files but are not interesting for our current dev. 
So we just want to have cscope connection for subfolder1.
Currently, when inside the mainwork folder, in vim, if you do` :cscode add ../subfold1/` , and try to find a definition from file1, you will get an error: "file1.c does not exist".
Same with nvim and :cs db add ../subfolder1/cscope.out

But, if you use` :cscope add ../subfold1/ ../subfold1/`, the file1 will be found.

Hope it make sense !
In attachment, you may find a example archive
[demo_pre_path.zip](https://github.com/user-attachments/files/15800636/demo_pre_path.zip)

**Comment by dhananjaylatkar** [comment]
I have exactly the same workflow.

In latest version of the plugin, I have implemented relative path functionality. This converts absolute paths to relative ones and you won't see big paths.

Here is what I do -

In `subfold1`
```sh
fd -e c -e h -a > cscope.files # use absolute paths
cscope -bqk # build db
```

In `nvim` -
```
:Cs db add ../subfold1/cscope.out

:Cs find f file1.c
```

Result will look like -
```
../subfold1/file1.c
```

Try this out.

**Comment by dhananjaylatkar** [comment]
I see your point.

But my concern is, as of now `:Cs db add` takes multiple db paths and I want to keep doing that.

One way could be -

Keep taking input as is i.e.
```
:Cs db add ../subfold1/cscope.out
```

And if `cscope` output is relative path, append parent from db path, `../subfold1/` in this case.

What do you think? Would it create any issues?

**Comment by mmaret-psee** [comment]
I think your solution make a lot of sens.

The only downside I can see ( not related to my use-case) is if you build a DB for your current folder but want to have it stored somewhere else.
Maybe that's a neat case ?

Another way, is it possible to change current command grammar ?
like:
`:Cs db add ../subfold1/cscope.out:../subfold1 ./cscope.out`

So `:` will be a possible separator for pre-path ?

**Comment by dhananjaylatkar** [comment]
I like this idea.

We can also have special symbol (maybe `@`) to indicate that parent of path is what should be prepended.

This will avoid duplicate typing.

```
:Cs db add ../subfold1/cscope.out:@
```

**Comment by mmaret-psee** [comment]
Thanks a lot !
