### ISSUE TITLE
Can I donate to this project?

### ISSUE THREAD

**Issue by Endle** [dhananjaylatkar/cscope_maps.nvim#39]
Buymeacoffee / github sponsor / ko-fi /...

This plugin is super helpful to me and I'd like to donate a cup of coffee

**Comment by dhananjaylatkar** [comment]
Thanks for your interest. I have added "Github Sponsor" link in repo.
[4086cbb](https://github.com/dhananjaylatkar/cscope_maps.nvim/commit/4086cbb0fa1553830a3a27e3efe57adf6ebe5531)
