### ISSUE TITLE
vim-plug configuration

### ISSUE THREAD

**Issue by Nevinskas** [dhananjaylatkar/cscope_maps.nvim#4]
Hi,
I'm trying to setup cscope_maps with the [vim-plug](https://github.com/junegunn/vim-plug), however, after copying the config from readme, I get Lua error:
```
Error detected while processing /home/tadas/.dotfiles/nvim/.config/nvim/init.vim:
line   43:
E5108: Error executing lua [string ":lua"]:1: module 'cscope_maps' not found:
        no field package.preload['cscope_maps']
        no file './cscope_maps.lua'
        no file '/usr/share/luajit-2.1.0-beta3/cscope_maps.lua'
        no file '/usr/local/share/lua/5.1/cscope_maps.lua'
        no file '/usr/local/share/lua/5.1/cscope_maps/init.lua'
        no file '/usr/share/lua/5.1/cscope_maps.lua'
        no file '/usr/share/lua/5.1/cscope_maps/init.lua'
        no file './cscope_maps.so'
        no file '/usr/local/lib/lua/5.1/cscope_maps.so'
        no file '/usr/lib/lua/5.1/cscope_maps.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

As far as I understand, the lua interpreted does not know the path to the `cscope_maps.lua`.
Is there something more additional should be included in `init.vim`?
[init.vim.zip](https://github.com/dhananjaylatkar/cscope_maps.nvim/files/11326521/init.vim.zip)

thanks!

**Comment by dhananjaylatkar** [comment]
Hi @Nevinskas,

Please put `require("cscope_maps").setup({})` after `call plug#end()`

**Comment by Nevinskas** [comment]
I can't believe, that this didn't cross my mind... :facepalm: 
Thanks!
