### ISSUE TITLE
Failed to run `config` for cscope_maps.nvim

### ISSUE THREAD

**Issue by cccheng** [dhananjaylatkar/cscope_maps.nvim#41]
**Describe the bug**
After upgrade to the latest [commit](https://github.com/dhananjaylatkar/cscope_maps.nvim/commit/6c2b6b7d8006a1b7b498408a71d1f33af690df25)，the following error is shown.

```
Failed to run `config` for cscope_maps.nvim

...cal/share/nvim/lazy/cscope_maps.nvim/lua/cscope/init.lua:498: attempt to concatenate local 'root' (a nil value) 

# stacktrace: 
  - /cscope_maps.nvim/lua/cscope/init.lua:498 _in_ **setup**
  - /cscope_maps.nvim/lua/cscope_maps/init.lua:29 _in_ **setup**
```

**To Reproduce**
open nvim

**Expected behavior**
no error shown

**nvim version (please complete the following information):**
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

**cscope_maps config (please complete the following information):**
```lua
opts = {
        skip_input_prompt = true,
        cscope = {
            picker = "telescope",
            project_rooter = {
                enable = true,
            },
        },
}
```

**Comment by dhananjaylatkar** [comment]
thanks! It is fixed now
