### ISSUE TITLE
cscope cannot read file version from file 

### ISSUE THREAD

**Issue by menash134** [dhananjaylatkar/cscope_maps.nvim#47]
**Describe the bug**
I use cscope and nvim . I dont use normal tags.
ctrl+5 to do the tags to browse. Normally works. Sometimes I get the following error

**To Reproduce**
Steps to reproduce the behavior in browsing linux source code.
1. Go to napi_gro_receive (ctrl+5)
2. Go to dev_gro_receive which is called in napi_gro_receive (ctrl+5)
3. Go to offload_base which is a static variable declared in the same file. (ctrl+5)
![image](https://github.com/user-attachments/assets/5065c816-4e1a-4fff-8035-ed69cdcf8d77)
and also there is a warning which is may be normal
![image](https://github.com/user-attachments/assets/4026f9a1-c978-4414-9aff-58f2cc31fa42)

**Expected behavior**
Expected behaviour to not show error in the image.

**Screenshots**

**nvim version (please complete the following information):**
0.10.0

**cscope_maps config (please complete the following information):**
Added as a screen shot.

![image](https://github.com/user-attachments/assets/f0a6570b-b51d-42d5-819c-dc1d337dc149)

**Additional context**

**Comment by dhananjaylatkar** [comment]
@menash134 

remove `cscope.out.in` and `cscope.out.po` from `db_file`.

No need to provide them. See https://cscope.sourceforge.net/cscope_man_page.html

**Comment by menash134** [comment]
Thank you  very much for your help. It worked.

**Comment by menash134** [comment]
Just a follow through, I need a small help. How to not use picker and its preview? 
Some old guys in our project, needs really old way of doing things. They don't like preview in the picker, just the list of the occurences is enough. How should I configure it? @dhananjaylatkar

**Comment by dhananjaylatkar** [comment]
```lua
{
  skip_input_prompt = true,
  cscope = {
    picker = "quickfix",
    -- size of quickfix window
    qf_window_size = 5,
    -- position of quickfix window
    qf_window_pos = "bottom", -- "bottom", "right", "left" or "top"
    -- "true" does not open picker for single result, just JUMP
    skip_picker_for_single_result = true,
  }
}
```

this should provide old school behaviour

**Comment by menash134** [comment]
![image](https://github.com/user-attachments/assets/cbdd15af-2764-41d2-8a8d-4b3171d1ee84)

Hi, I tried this for eg: when you try sk_buff , there are mulitple occurences which are previewed like this. Can we configure this preview to be false some where

![image](https://github.com/user-attachments/assets/784558b5-b7b8-48ba-b216-d910ec8ec6d2)

**Comment by dhananjaylatkar** [comment]
If you don't see a list of results then how would you go to a particular occurrence?

Anyway, it's a quickfix window. You can use `:cclose` to close it.

**Comment by dhananjaylatkar** [comment]
That preview is not inbuilt neovim behaviour.
You must be using some plug-in to show preview for quickfix entries. Please disable that.

**Comment by menash134** [comment]
@dhananjaylatkar  Thanks for the response.
 In the above picture there are two window, quickfix and quickfix preview. 
I just need the quickfix window alone and not the preview.
In another words, the results should be there but not the preview. Hope Iam clear in the words.

**Comment by menash134** [comment]
oh ok.. I check that
