### ISSUE TITLE
Provide installation option for `.vim/bundle`

### ISSUE THREAD

**Issue by Letme** [dhananjaylatkar/cscope_maps.nvim#52]
**Is your feature request related to a problem? Please describe.**
I am trying to install the plugin, but I do not use the lazy.vim plugin - I use pathogen and submodule plugins to `.vim/bundle`. When I do it with this plugin it does not work.

I have added the setup command in my vim, but it tells me that there is error while processing vimrc file, `not editor command require("cscope_maps").setup()`

**Describe the solution you'd like**
Get it working when I submodule the plugin into `.vim/bundle`

**Describe alternatives you've considered**
Tried various variations of the setup command to see if plugin is detected but it is not. There is also no `:cscope` command.

**Additional context**
Using Neovim 0.9.5

**Comment by dhananjaylatkar** [comment]
please paste your vimrc contents related to this plugin

**Comment by Letme** [comment]
```
"
" Cscope in NeoVim
"
require("cscope_maps").setup()
```

**Comment by dhananjaylatkar** [comment]
change it to this -
```
"
" Cscope in NeoVim
"
lua require("cscope_maps").setup()
```

**Comment by Letme** [comment]
OK, that works. Thanks for the quick fix. 

Do you want me to add the pathogen installation path, or just this addition of lua was needed for everyone?

**Comment by dhananjaylatkar** [comment]
Try running `:Cscope help`. If it work then no need to add path

**Comment by Letme** [comment]
Plugin works with just above change - I did nothing else.
