### ISSUE TITLE
`db show` raises error "expected string, got nil"

### ISSUE THREAD

**Issue by rockyzhang24** [dhananjaylatkar/cscope_maps.nvim#54]
**Describe the bug**
See the screenshot below please.

**To Reproduce**
Run `:Cscope db build` followed by `:Cs db show`. 

**Expected behavior**
Should show the db and no errors

**Screenshots**
<img width="1361" alt="image" src="https://github.com/user-attachments/assets/ca6c76c6-bb53-40eb-a5d5-91e68825bd7e">

**nvim version (please complete the following information):**
I am using the nightly neovim.
NVIM v0.11.0-dev-740+g4c5bce9cb

**cscope_maps config (please complete the following information):**
```lua
require('cscope_maps').setup({
  cscope = {
    exec = 'gtags-cscope',
    project_rooter = {
      enable = true,
    },
  },
})
```

**Additional context**
No. 

Thank you!

**Comment by dhananjaylatkar** [comment]
Hi @rockyzhang24 
I'm not able to repro this but see some null value in db.
Can you try fix from `db-path` branch? I can merge if it fixes your issue

**Comment by rockyzhang24** [comment]
Hello. It works perfectly. Thank you for the quick fix.
