### ISSUE TITLE
wrong root dir for search results

### ISSUE THREAD

**Issue by bon-ami** [dhananjaylatkar/cscope_maps.nvim#59]
**Describe the bug**
Windows 10. cscope: version 15.8a
My neovim's path is used as project root in search results and thus I cannot go to the references.
I remember, it showed wrong but clicking one did go to the right file, when I first installed this plugin yesterday.
Now it both showed and pointed wrong.

**To Reproduce**
1. open a .c file
2. change current directory to the root of the project using `:cd projecct root`. `:echo getcwd()` shows it is correct.
3. find a function, such as xyz.
4. `:Cs f g`
5. (It shows sth. like `neovim root/b.c xyz`
6. click a found reference and `neovim root/b.c` is opened, which does not exist.

**Expected behavior**
in quickfix list, sth. like `project root/b.c xyz` and clicking it goes to it.

**Screenshots**

**nvim version (please complete the following information):**
0.10.2

**cscope_maps config (please complete the following information):**
```lua
opts = {}
```

**Additional context**
this plugin is installed with Plug.

**Comment by bon-ami** [comment]
`:Cs db show` shows it under `neovim root`. So it seems cscope is using cwd when my neovim starts and does not change when cwd changes and I run `:Cs`.
how to automatically un-include it please? Thanks.

**Comment by dhananjaylatkar** [comment]
It's expected behaviour.

You can add absolute path to cscope.db
e g
```lua
opts = {
  cscope = {
    db_file = { "/abs/path/to/project/cscope.out:@" }
  }
}
```

**Comment by bon-ami** [comment]
So it worked yesterday maybe b/c I sourced init.vim again when pwd already changed.
In addition, how to remove one, b/c windows driver letters precede colons. :Cs db rm cscope.out:C:/root fails.

**Comment by dhananjaylatkar** [comment]
Decisions regarding `db` path were taken without considering Windows. Let me think about Windows support.

**Comment by dhananjaylatkar** [comment]
hi @bon-ami 

pls check if `windows` branch fixes your issue https://github.com/dhananjaylatkar/cscope_maps.nvim/tree/windows

I have added `:Cs reload` command which reloads the config. You can use it when you change the directory. Check `:h DirChanged` if you want to automate `reload`.

Another way is to use absolute path method mentioned in previous method.

i'll merge if it's all right from your side

**Comment by bon-ami** [comment]
It's so kind of you. I'm neither familiar with vim scripts or lua. So I cannot provide many options on your changes. In general, I agree with your changes, as long as it supports both add and rm of db, at least. In addition, you may also want to modify README.
 I'm not sure about the part of normalizing the string, though it seems in concept correct.
 As for the drive letter support, I hope it supports both relative and absolute paths, that's to say, with and without driver letters.
```
M.separate_fname = function(path, sep)
...
	if vim.fn.has("win32") and #file == 1 then
```

**Comment by dhananjaylatkar** [comment]
I want you to test the `windows` branch and lmk if it satisfies your use case.
You can point to this branch using your plugin manager.

**Comment by bon-ami** [comment]
Pitty, it's not correct.
1.  cd to d:/a
2. `:Cs reload` works fine. Now it's
```
cscope: 1) db=cscope.out pre_path=d:/a
```
3. testing with a file not exists. `:Cs db add c:tm` incorrect. I hope it is `db=c pre_path=d:/a/tm`, but it is
```
cscope: 2) db=c:tm pre_path=d:/a
```
4. `:Cs db add c:c:/tm` incorect. I hope it is `db=c pre_path=c:/tm`, but it is
```
cscope: 3) db=c:c pre_path=/tm
```
5. create an empty d:/apps/cscope.out and `:Cs db add cscope.out:d:/apps`
```
cscope: 4) db=cscope.out pre_path=d
```

**Comment by dhananjaylatkar** [comment]
I was trying to avoid changing db_path grammar but I don't see any better way to achieve this.

I have changed path separator to `::`. Please check updated code.

**Comment by bon-ami** [comment]
I've found your previous error. in `separate_fname`, you should concatenate sp[2] and [3] for other, instead of file.
Also using more `M.sep` in #61, branched from your windows.
Not solving the stack highlight issue.

**Comment by dhananjaylatkar** [comment]
Following case will not work in your change 
C:C:/tm

C:/tm:C

It's better to have `::` and avoid this confusion 
C::C:/tm

C:/tm::C

**Comment by bon-ami** [comment]
> Following case will not work in your change C:C:/tm
> 
> C:/tm:C
> 
> It's better to have `::` and avoid this confusion C::C:/tm
> 
> C:/tm::C

I first tested my change with `:Cs db add d:C:/a` and `:Cs db show` "db=d pre_path=C:/a"
anyway, it's your decision. double colons is clearer while you loses compatibility to previous versions.
