### ISSUE TITLE
cscope: [build] out:  cscope: no source files found^M cscope: database build failed

### ISSUE THREAD

**Issue by TSalmon3** [dhananjaylatkar/cscope_maps.nvim#6]

**Comment by TSalmon3** [comment]
Run `:Cscope build` failed

**Comment by dhananjaylatkar** [comment]
`cscope` needs cscope.files to build database.

Make sure you have cscope.files present in cwd.

If you have `fd`, use `fd -e c -e h > cscope.files`

**Comment by dhananjaylatkar** [comment]
PS. This plugin is only tested on Linux (Fedora and Ubuntu to be precise).

I don't have windows machine to test.

**Comment by TSalmon3** [comment]
It can run. I substiute `args = { "-Rbk"}` for `args = { "-bqkv"}`.

**Comment by dhananjaylatkar** [comment]
That's good to know.

Did you try generating cscope.files?

**Comment by TSalmon3** [comment]
yes, It has same question when I run fd to generate `cscope.files`.
...
cscope: no source files found^M
cscope: database build failed
...

**Comment by TSalmon3** [comment]
$ fd -e c -e h > cscope.files
$ cscope.exe -bqkv  
cscope: cannot find file ��a
cscope: no source files found

**Comment by dhananjaylatkar** [comment]
I'll need more info.
What are the contents of cscope.files?
Do you have `fd` installed?
Are you using cmd prompt or powershell?

Also see 2nd step here, https://courses.cs.washington.edu/courses/cse451/12sp/tutorials/tutorial_cscope.html
