### ISSUE TITLE
Doesn't work well with GNU gtags

### ISSUE THREAD

**Issue by durd07** [dhananjaylatkar/cscope_maps.nvim#62]
As code shows:

https://github.com/dhananjaylatkar/cscope_maps.nvim/blob/main/lua/cscope/init.lua#L550
```
	if M.opts.exec == "gtags-cscope" then
		M.opts.db_file = gtags_db
	end
```

if exec set to `gtags-cscope` then db_file will be hardcoded into `GTAGS`, this will override the configuration from user.

Further more, seems this plugin doesn't work perfectly with `ludovicchabant/vim-gutentags` in gtags-cscope.
Could you please add some similar features like auto find the db_file within parent directories recursively?

Thanks very much.

**Comment by dhananjaylatkar** [comment]
See `cscope.project_rooter` option. It finds db file in parent directory.

Does gtags allow filename other than `GTAGS`?

**Comment by durd07** [comment]
Hi @dhananjaylatkar Thanks very much for your response.

Please forgive me for having little technical knowledge about neovim extensions.
I went through your code and have a basic understanding of what you want to do with project_rooter.

Now I understand how to use the project_rooter.
you use `vim.fs.root(vim.fn.getcwd(), primary_conn.file)` to get the root directory, so I need to fake touch a new GTAGS at the root directory, then use `Cs db build` to recreate the GTAGS file. If there is no GTAGS files at the root directory initially, it can't find the root.

**Comment by dhananjaylatkar** [comment]
This plugin assumes that you have already created `db_file` for `project_rooter` to work. 
Use case for this is as follows -
1. create cscope db in root
2. move to project subdir and open nvim
3. `project_rooter` will detect that this is subdir and use `db_file` from project root for cscope queries.

`:Cs db build` works without having dummy file. The catch here is, if db_file is not present then it'll be created in current directory.
You might want to configure `cscope.db_build_cmd_args` to get desired results.
