### ISSUE TITLE
Open in new split

### ISSUE THREAD

**Issue by spikeh** [dhananjaylatkar/cscope_maps.nvim#8]
Is it possible to open a new search query in a new split, like cscope in vim using e.g. `scs`?

**Comment by dhananjaylatkar** [comment]
If you are using Telescope, then use <kbd>C-x</kbd> for horizontal split and <kbd>C-v</kbd> for vertical split.

**Comment by dhananjaylatkar** [comment]
If you are using Telescope, then use <kbd>C-x</kbd> for horizontal split and <kbd>C-x</kbd> for vertical split.

For QuickFix, <kbd>C-w Enter</kbd> for horizontal split. Vertical split is not that straightforward, you can check [this](https://stackoverflow.com/questions/16743112/open-item-from-quickfix-window-in-vertical-split) SO answers.
